/**
 * PK-02 — shell completion is DERIVED from the CLI's real command surface.
 *
 * The bug worth preventing: someone adds a subcommand, ships it, and the completion script still
 * offers the six commands it knew about a year ago. So the completion is generated by parsing the
 * binary's own `help`, and these tests pin the parser — because if the parser silently returns
 * nothing, the generator would happily emit an empty, well-formed, useless completion script.
 */

import { describe, expect, it } from 'vitest';

import { parseHelp } from '../../scripts/package-cli.ts';

// The CLI's actual help text, including the wrapped continuation line that made the naive
// "every indented line is a command" parser produce a command called `approval`.
const HELP = `qwen-harness <command>

  doctor                 report environment, config provenance, sandbox, credential presence
  run <prompt>           run one turn in the current workspace and print the result
  sessions               list the sessions in this workspace
  resume <id> [prompt]   continue a session; with no prompt, resume a pending
                         approval and finish the SAME turn
  fork <id>              create a new session forked from an existing one
  export <id>            print a session as portable JSONL

  flags: --profile <plan|ask|auto-accept-edits|yolo>  --model <name>  --json
`;

describe('parseHelp', () => {
  const surface = parseHelp(HELP);

  it('finds every command', () => {
    expect(surface.commands.map((c) => c.name)).toEqual([
      'doctor',
      'run',
      'sessions',
      'resume',
      'fork',
      'export',
    ]);
  });

  it('does NOT invent a command out of a wrapped continuation line', () => {
    // `resume`'s summary wraps onto a second, deeply-indented line beginning "approval and…".
    // A sloppier parser turns that into a command named `approval`.
    expect(surface.commands.map((c) => c.name)).not.toContain('approval');
  });

  it('keeps the summary, so zsh and fish can explain each command', () => {
    const doctor = surface.commands.find((c) => c.name === 'doctor');
    expect(doctor?.summary).toContain('report environment');
  });

  it('extracts the flags and the profile choices', () => {
    expect(surface.flags).toEqual(['--profile', '--model', '--json']);
    expect(surface.profiles).toEqual(['plan', 'ask', 'auto-accept-edits', 'yolo']);
  });

  it('does not treat a flag as a command', () => {
    expect(surface.commands.map((c) => c.name).some((n) => n.startsWith('-'))).toBe(false);
  });

  it('returns nothing for help text with no commands — the generator refuses to ship that', () => {
    // `package-cli.ts` throws when this is empty rather than writing an empty completion.
    expect(parseHelp('qwen-harness <command>\n').commands).toEqual([]);
  });

  it('picks up a command added later, with no change to this parser', () => {
    // The regression that motivates generating rather than hand-writing completions.
    const extended = HELP.replace(
      '  fork <id>',
      '  mcp <action>           manage MCP servers\n  fork <id>',
    );
    expect(parseHelp(extended).commands.map((c) => c.name)).toContain('mcp');
  });
});
